apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/argoproj/argo-cd/manifests/ha/cluster-install?ref=v2.3.3

patchesStrategicMerge:
- argocd-application-controller-clusterrolebinding.yaml
- argocd-cm.yaml
- argocd-server-clusterrolebinding.yaml
- argocd-server-service.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: argocd-repo-server
  path: argocd-application-controller-deployment-command-log-level.yaml
